### ISSUE TITLE
Fern miscategorized as "Animal"

### ISSUE THREAD

**Issue by cmil** [dh-network/ecocor-extractor#7]
In https://github.com/EcoCor/ecocor-extractor/blob/main/word_list/english/animal_plant-en.json, the entry for "fern", Wikidata ID Q80005, is categorized as "Animal" while it actually should be a "Plant".

Does this hint at some flaw in how the list is created or is it just a singular random mistake?

_Suggestion:_ Could we format the JSON files with line breaks and indentation? It would make it easier to refer to individual entries and lines.

**Comment by hsluytergaethje** [comment]
I'm not sure why that't the case, maybe @DanilSko you have an idea? 

As for the layout: Yes, I'll do that.

**Comment by DanilSko** [comment]
> Does this hint at some flaw in how the list is created

I bet it does. This 'Fern' thingie is an **instance of Q55983715 'organisms known by a particular common name'** so you can't just trace it to any 'animal' or 'plant' superclass. Wikidata is of limited help when it comes to animal/plant differentiation for this class of objects. And yet 'organisms known by a particular common name' is exactly where most 'non-scientific' colloquial names for animals and plants can be found.  Of course, one can implement a number of heuristics (e.g. in this particular case there seems to be also 'Property:P642' which is pointing toward 'Polypodiopsida (Q373615)' which can be eventually classified as plant by hopping across the 'parent taxon' relations.. but the 'P642' property does not exist consistently in such cases, it is even listed as a deprecated property of wikidata) And since it was a 2-days hackathon, only a limited number of such heuristics was applied. I'll try to produce a cleaner list though.

**Comment by DanilSko** [comment]
Maybe we could use the 'KBPedia ID (Property:P8408)'  link, this KBPedia seems to know fern is a plant (https://kbpedia.org/knowledge-graph/reference-concept/?uri=Fern), and 'KBPedia ID (Property:P8408)' seems to exist for many other 'organisms known by a particular common name'. I'll give it a try.

**Comment by DanilSko** [comment]
Ok, so I wen through all entities in this JSON and checked all the non-obvious ones. There were about 50-55 plants misclassified as animals, and about 5-10 fungi. I fixed them here : https://github.com/EcoCor/ecocor-extractor/commit/71e7d48ca92ab7c2baf8222ba546287cc97d60b5, https://github.com/EcoCor/ecocor-extractor/commit/8c7efe227b4eb00e8b91b3016cdcddd061cd9d6f, https://github.com/EcoCor/ecocor-extractor/commit/5e256759661d2456079edad1a890e89144802021, https://github.com/EcoCor/ecocor-extractor/commit/7e4ff07f81183fd6c8303787867bf1f559705e2e, https://github.com/EcoCor/ecocor-extractor/commit/8b3b6661e80b92831798dfdbaea7eda25c53e020, https://github.com/EcoCor/ecocor-extractor/commit/de93a303c38d5645024ce911a24059dc79f1450f, https://github.com/EcoCor/ecocor-extractor/commit/3d4620563988e4f9485d2633921bad34ab0a8f76, https://github.com/EcoCor/ecocor-extractor/commit/57a8b963d31023f89bedcecea0086412c38f29c9, https://github.com/EcoCor/ecocor-extractor/commit/d91ddba2fd28bcdbddf3ffa4cf9aa8d7dfa01b85
